# Generated by Django 5.2 on 2025-04-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='meta_title',
        ),
    ]
