# Generated by Django 5.2 on 2025-05-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_lead_testimonial_alter_project_project_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_heading',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
