# Generated by Django 5.2 on 2025-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_blog_heading_blog_title_blog_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_description_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
