# Generated by Django 5.2 on 2025-05-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_blog_description_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='service',
            new_name='budget',
        ),
    ]
