# Generated by Django 5.2 on 2025-05-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_service_lead_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='budget',
            new_name='city',
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_budget',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='zipcode',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
