# Generated by Django 5.2 on 2025-05-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_budget_lead_city_lead_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='country',
            new_name='project_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='state',
        ),
        migrations.AddField(
            model_name='lead',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
